### ISSUE TITLE
JavaScript example not working

### ISSUE THREAD

**Issue by doodlemoonch** [zingchart/gitbook-plugin-code-editor#2]
I can't get the javascript example working, it still renders as html

```
{% codeeditor src='./inline-expression-old.js', language='javascript', theme='github' %}
{% endcodeeditor %}
```

<img width="797" alt="screen shot 2016-07-15 at 08 50 15" src="https://cloud.githubusercontent.com/assets/213453/16867349/478f1a14-4a69-11e6-8f43-6f8a6aacc707.png">

**Comment by christie-sorenson** [comment]
Sorry for the problems.  Quick question:  Is the problem that it is not highlighting or not running properly? 

I've used your code and do see the syntax highlighting, so I'm trying to figure out why it isn't working for you.  What browser are you using?  Does taking the theme off change anything?  If you put HTML in, is it highlighting properly?  

It would definitely not run properly since it is expecting HTML.  I do have 'js' and 'css' tabs that are currently hidden, but I'll be working on those in the future.

**Comment by doodlemoonch** [comment]
Ah ok, I started hacking away at getting the js tab to work. Will try to contrib if I get the time
